version: '2'
services:

  web:
    build: ./app
    command: nodemon ./server.js
    ports:
      - 8080:8080
    volumes:
      - ./app:/data
    depends_on:
      - db
    environment:
      DATABASE_URL: mongodb://mongodb@db/exchange-rate

  db:
    image: mongo:latest